repos:
  - repo: local
    hooks:
      - id: flutter-format
        name: Flutter Format
        entry: dart format --set-exit-if-changed .
        language: system
        pass_filenames: false
        always_run: true

      - id: flutter-analyze
        name: Flutter Analyze
        entry: flutter analyze
        language: system
        pass_filenames: false
        always_run: true

      - id: flutter-test
        name: Flutter Test
        entry: flutter test
        language: system
        pass_filenames: false
        stages: [push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: ^(assets/translations/.*\.json)$