// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPLmkg8Olp4m52Iw0XgS8uVo6mgcztkhc',
    appId: '1:1073236964282:web:bc2bb6ea04703890fde383',
    messagingSenderId: '1073236964282',
    projectId: 'flutter-boidlerplate-riverpod',
    authDomain: 'flutter-boidlerplate-riverpod.firebaseapp.com',
    storageBucket: 'flutter-boidlerplate-riverpod.firebasestorage.app',
    measurementId: 'G-4MKD1V5S4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBANBWTbfB6ktejfhxpl05yWPZDzxIf2cU',
    appId: '1:1073236964282:android:43c1d61411bdd42ffde383',
    messagingSenderId: '1073236964282',
    projectId: 'flutter-boidlerplate-riverpod',
    storageBucket: 'flutter-boidlerplate-riverpod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXsdM6LX_99A5E62xL7UASP_3bvdfg1Jc',
    appId: '1:1073236964282:ios:0e6170ebea7de7d4fde383',
    messagingSenderId: '1073236964282',
    projectId: 'flutter-boidlerplate-riverpod',
    storageBucket: 'flutter-boidlerplate-riverpod.firebasestorage.app',
    iosBundleId: 'com.example.learnRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXsdM6LX_99A5E62xL7UASP_3bvdfg1Jc',
    appId: '1:1073236964282:ios:0e6170ebea7de7d4fde383',
    messagingSenderId: '1073236964282',
    projectId: 'flutter-boidlerplate-riverpod',
    storageBucket: 'flutter-boidlerplate-riverpod.firebasestorage.app',
    iosBundleId: 'com.example.learnRiverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPLmkg8Olp4m52Iw0XgS8uVo6mgcztkhc',
    appId: '1:1073236964282:web:36a8a5b7b9992c0bfde383',
    messagingSenderId: '1073236964282',
    projectId: 'flutter-boidlerplate-riverpod',
    authDomain: 'flutter-boidlerplate-riverpod.firebaseapp.com',
    storageBucket: 'flutter-boidlerplate-riverpod.firebasestorage.app',
    measurementId: 'G-RZV8870VYK',
  );
}
